### ISSUE TITLE
DaBible Foundation Onboarding Checklist for Olumese Ikhuoria

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#142]
Congratulations Olumese,

We are very excited that you will be joining our team of volunteers to bring the word of God to our generation. This checklist will help you to understand how we work, and easily integrate you into our work environment.

# Your onboarding checklist
Take your time, the following checklist will guide you to onboard easily. **Tick off each task completed.** 

- [x] Read the [HOME SECTION](https://github.com/DaBible-Foundation/DaBible-MainHub/wiki) of our Handbook  - (Reading time: 3mins)
- [x] Read [how we work at DaBibe Foundation](https://github.com/DaBible-Foundation/DaBible-MainHub/wiki/How-we-work-at-DaBible-Foundation-using-GitHub) on our handbook. - (Reading time: 2mins)
- [x] Read about [how we communicate.](https://github.com/DaBible-Foundation/DaBible-MainHub/wiki/How-we-communicate%3F-Slack) Slack! Slack!! Slack!!!  - (Reading time: 2mins)
- [x] Create your first issue! -  (Login or create a user account on GitHub)

  Here, everything starts with an issue, then we use slack to communicate about the issue. Your first issue is to [create a request to join our slack account](https://github.com/DaBible-Foundation/DaBible-MainHub/issues/new?assignees=sanmiayotunde&labels=documentation&template=join-slack-channel.md&title=Request+to+Join+DaBible+Foundation+Slack+Channel&project=Team-Management-Issues).

   Enter the following information in the issue. Your first and last name, location, email, and  why I want to join DaBible Foundation: 

- [x] Download slack to your phone and PC.
- [x] Watch a video about how to use slack | [Video Link](https://youtu.be/m2JuAa6-ors) (Est Time: 1mins 22seconds)
- [x] Understand how to use threads in slack - [Text](https://slack.com/help/articles/115000769927-Use-threads-to-organize-discussions-) | [Video](https://youtu.be/eBSMwpy2Hqg) (Est Time: 3mins)
- [x] We have a weekly sprint planning and reporting meeting on Saturdays 10 AM EST on GoogleMeet, and the meeting is always recorded.  [Watch any two of our latest recordings](https://drive.google.com/drive/folders/1yVs8BdZ2rSNaMs-SqNNyVgEA6E_yDNgn?usp=sharing), and kindly pay attention to how we use the reporting spreadsheet. 
  - [x] Watched the first  video
  - [x] Watched second video
- [x] Study our [weekly reporting spreadsheet](https://docs.google.com/spreadsheets/d/1ftt0jagVQvCvgfepI5Ouuob5UY9EL2epfn5dC7P3wfI/edit#gid=0) and pay attention to WENT WELL, IMPROVE & ACTIONS section.   - (Reading time: 5mins)
- [x] Visit our [Data Studio](https://datastudio.google.com/u/0/reporting/0004bec3-6b8e-4f83-98f2-766ef76d8b24/page/Y4oY) to see our current users' analytics.   - (Reading time: 4mins)
- [x] Read about our [Branding section](https://github.com/DaBible-Foundation/DaBible-MainHub/wiki/Branding-Colors) on the handbook.   - (Reading time: 2mins)
- [x] Close this issue, and celebrate yourself!!!!
