### ISSUE TITLE
RCCG SEMINARY - We will be supporting the school to revamp their website and create short YouTube Ads that will be served to Nigerians living abroad who watch african movies.

### ISSUE THREAD

**Issue by olumese** [DaBible-Foundation/DaBible-MainHub#218]
**Please describe the task or issue:**

- [x] Youtube Video Ad => (Paste Final Model Video Here

- [x] Find examples of Universities running YouTube video advertisements. 

- [x] Pick a video as our model for the new video we will be creating.  

- [x] Pick out small fragments from this existing video to create another new video ad.] 

- [x] Website Revamp

- [x] Contact the current website administrator to establish a joint effort

 

- [x] Develop UX Design for the Bachelor's Degree webpage before writing any code

**Additional information:**

-
