### ISSUE TITLE
Saturday Meeting Checklist

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#294]
- [ ] Create/Send out slide by thursday
- [ ] Saturday discuss about communication
- [ ] Reach out to team on Friday
